//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saraf365.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankCard()
        {
            this.CartTransferHistory = new HashSet<CartTransferHistory>();
        }
    
        public long xID { get; set; }
        public string xCardHolderName { get; set; }
        public byte xType { get; set; }
        public string xBankName { get; set; }
        public string xAccountNumber { get; set; }
        public string xCardNumber { get; set; }
        public string xInternetUsername { get; set; }
        public string xInternetPassword { get; set; }
        public Nullable<long> xMinToTransfer { get; set; }
        public string xSecondPassword { get; set; }
        public string xCvv2 { get; set; }
        public string xExpireMonth { get; set; }
        public string xExpireYear { get; set; }
        public long xBalance { get; set; }
        public bool xIsActive { get; set; }
        public string xDepositStatus { get; set; }
        public string xLastLoginStatus { get; set; }
        public long xBannedAmount { get; set; }
        public int xFailedLoginCount { get; set; }
        public Nullable<long> xMinDeposit { get; set; }
        public Nullable<System.DateTime> xLastUsageDate { get; set; }
        public string xSpecialConfigs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartTransferHistory> CartTransferHistory { get; set; }
    }
}
