//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saraf365.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public long xID { get; set; }
        public long xTicketID { get; set; }
        public string xBody { get; set; }
        public string xResponse { get; set; }
        public Nullable<System.DateTime> xResponseDate { get; set; }
        public System.DateTime xDate { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
