//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saraf365.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileData
    {
        public long xID { get; set; }
        public long xSystemnFileID { get; set; }
        public byte[] xData { get; set; }
        public bool xIsThumbnail { get; set; }
    
        public virtual SystemFile SystemFile { get; set; }
    }
}
