//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saraf365.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialLog
    {
        public long xID { get; set; }
        public Nullable<long> xUserID { get; set; }
        public byte xType { get; set; }
        public double xAmount { get; set; }
        public string xAddBy { get; set; }
        public System.DateTime xDate { get; set; }
        public string xDescription { get; set; }
    
        public virtual User User { get; set; }
    }
}
