//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saraf365.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gateway
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gateway()
        {
            this.Transaction = new HashSet<Transaction>();
        }
    
        public long xID { get; set; }
        public string xName { get; set; }
        public byte xType { get; set; }
        public long xMaxDailyAmount { get; set; }
        public bool xIsActive { get; set; }
        public string xConfig { get; set; }
        public double xActiveforLevelsAbove { get; set; }
        public bool xIsPrimary { get; set; }
        public double xCommisionPercent { get; set; }
        public bool xIsVip { get; set; }
        public long xMinBuyIn { get; set; }
        public bool xAllowCustomAmountForBuyIn { get; set; }
        public long xTodayTotalTransactionAmounts { get; set; }
        public System.DateTime xLastSuccessTransactionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
