//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saraf365.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Saraf365Entities : DbContext
    {
        public Saraf365Entities()
            : base("name=Saraf365Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<AdminNotification> AdminNotification { get; set; }
        public virtual DbSet<AdminRole> AdminRole { get; set; }
        public virtual DbSet<BankCard> BankCard { get; set; }
        public virtual DbSet<CartTransferHistory> CartTransferHistory { get; set; }
        public virtual DbSet<Conversation> Conversation { get; set; }
        public virtual DbSet<FileData> FileData { get; set; }
        public virtual DbSet<ScheduleMessage> ScheduleMessage { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<SystemFile> SystemFile { get; set; }
        public virtual DbSet<SystemLog> SystemLog { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<UserBankAccount> UserBankAccount { get; set; }
        public virtual DbSet<Withdrawal> Withdrawal { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<FinancialLog> FinancialLog { get; set; }
        public virtual DbSet<Gateway> Gateway { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<TelegramSupport> TelegramSupport { get; set; }
    }
}
