//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saraf365.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.CartTransferHistory = new HashSet<CartTransferHistory>();
        }
    
        public long xID { get; set; }
        public long xUserID { get; set; }
        public long xGatewayID { get; set; }
        public System.DateTime xDate { get; set; }
        public long xAmount { get; set; }
        public bool xVerified { get; set; }
        public string xPaymentInfo { get; set; }
        public double xComissionPercent { get; set; }
        public double xComissionAmount { get; set; }
        public string xBankRef { get; set; }
        public string xInvoice_key { get; set; }
        public double xCurrencyAmount { get; set; }
        public long xCurrencyExchangeRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartTransferHistory> CartTransferHistory { get; set; }
        public virtual Gateway Gateway { get; set; }
        public virtual User User { get; set; }
    }
}
