//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saraf365.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserBankAccount()
        {
            this.Withdrawal = new HashSet<Withdrawal>();
        }
    
        public long xID { get; set; }
        public long xUserID { get; set; }
        public string xBankType { get; set; }
        public string xCartNumber { get; set; }
        public string xShebaNumber { get; set; }
        public string xAccountNumber { get; set; }
        public bool xIsVerified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Withdrawal> Withdrawal { get; set; }
        public virtual User User { get; set; }
    }
}
